/*___INFO__MARK_BEGIN__*/
/*************************************************************************
 * 
 *  The Contents of this file are made available subject to the terms of
 *  the Sun Industry Standards Source License Version 1.2
 * 
 *  Sun Microsystems Inc., March, 2001
 * 
 * 
 *  Sun Industry Standards Source License Version 1.2
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.2 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
 * 
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 * 
 *   The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 * 
 *   Copyright: 2001 by Sun Microsystems, Inc.
 * 
 *   All Rights Reserved.
 * 
 ************************************************************************/
/*___INFO__MARK_END__*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_grid_drmaa_impl_slurm_Sessionimpl */

#ifndef _Included_com_sun_grid_drmaa_impl_slurm_SessionImpl
#define _Included_com_sun_grid_drmaa_impl_slurm_SessionImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SUSPEND
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SUSPEND 0L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RESUME
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RESUME 1L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_HOLD
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_HOLD 2L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RELEASE
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RELEASE 3L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TERMINATE
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TERMINATE 4L
/* Inaccessible static: JOB_IDS_SESSION_ALL */
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TIMEOUT_WAIT_FOREVER
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TIMEOUT_WAIT_FOREVER -1LL
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TIMEOUT_NO_WAIT
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_TIMEOUT_NO_WAIT 0LL
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_UNDETERMINED
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_UNDETERMINED 0L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_QUEUED_ACTIVE
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_QUEUED_ACTIVE 16L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SYSTEM_ON_HOLD
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SYSTEM_ON_HOLD 17L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_ON_HOLD
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_ON_HOLD 18L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_SYSTEM_ON_HOLD
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_SYSTEM_ON_HOLD 19L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RUNNING
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_RUNNING 32L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SYSTEM_SUSPENDED
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_SYSTEM_SUSPENDED 33L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_SUSPENDED
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_USER_SUSPENDED 34L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_DONE
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_DONE 48L
#undef com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_FAILED
#define com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_FAILED 64L
/*
 * Class:     com_sun_grid_drmaa_impl_slurm_SessionImplSlurm
 * Method:    nativeControl
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeControl
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeExit
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeGetContact
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeGetContact
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeGetDRMSInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeGetDRMSInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeGetJobProgramStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeGetJobProgramStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeRunBulkJobs
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeRunBulkJobs
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeRunJob
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeRunJob
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeSynchronize
 * Signature: ([Ljava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeSynchronize
  (JNIEnv *, jobject, jobjectArray, jlong, jboolean);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeWait
 * Signature: (Ljava/lang/String;J)Lcom/sun/grid/drmaa/SGEJobInfo;
 */
JNIEXPORT jobject JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeWait
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeAllocateJobTemplate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeAllocateJobTemplate
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeSetAttributeValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeSetAttributeValue
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeSetAttributeValues
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeSetAttributeValues
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeGetAttributeNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeGetAttributeNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeGetAttribute
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeGetAttribute
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_sun_grid_drmaa_impl_slurm_Sessionimpl
 * Method:    nativeDeleteJobTemplate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sun_grid_drmaa_impl_slurm_SessionImplSlurm_nativeDeleteJobTemplate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
