CREATE SCHEMA "usr" AUTHORIZATION tao;
CREATE SCHEMA "common" AUTHORIZATION tao;
CREATE SCHEMA "topology" AUTHORIZATION tao;
CREATE SCHEMA "component" AUTHORIZATION tao;
CREATE SCHEMA "product" AUTHORIZATION tao;
CREATE SCHEMA "workflow" AUTHORIZATION tao;
CREATE SCHEMA "execution" AUTHORIZATION tao;
CREATE SCHEMA "scheduling" AUTHORIZATION tao;